server:
  port: 8082
spring:
  cloud:
    bootstrap:
      enabled: true
  application:
    name: AuthService
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka