spring:
  datasource:
    url: jdbc:h2:file:../database/lmsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-ui