swe:
  lms:
    auth:
      api:
        cookie_token: LMS_TOKEN
        cookie_user: LMS_USER
        cookie_role: LMS_ROLE
token:
  key: swede
  issuer: sweproject

logging:
  level:
    root: ERROR
    org:
      spring:
        framework: ERROR