const env = process.env;

const Constants = {
    BASE_URL: env.REACT_APP_BASE_URL,
    ADMIN_URL: env.REACT_APP_ADMIN_URL,
    AUTH_URL: env.REACT_APP_AUTH_URL,
    BOOK_URL: env.REACT_APP_BOOK_URL,
    AUTH_REALM: env.REACT_APP_AUTH_REALM,
    AUTH_CLIENT_ID: env.REACT_APP_AUTH_CLIENT_ID,
    LIMIT_PER_FETCH: env.REACT_APP_LIMIT_PER_FETCH,
    HOME_TYPE: ['CONDO', 'HDB', 'BUILDING', 'APARTMENT', 'HOUSE', 'TRAILER'],
    PROPERTY_TYPE: ['SELL', 'RENT'],
    ROLE: {
        ADMIN: 'ADMIN',
        LIBRARIAN: 'LIBRARIAN',
        USER: 'USER',
    },
    ROLE_NAME: ['ADMIN', 'LIBRARIAN', 'USER'],
    OWNER_ROLE: 'OWNER',
    ADMIN_ROLE: 'ADMIN',
    CUSTOMER_ROLE: 'CUSTOMER',
    AUTH_TOKEN: env.REACT_APP_AUTH_TOKEN,
    COOKIE: {
        LMS_TOKEN: 'LMS_TOKEN',
        LMS_ROLE: 'LMS_ROLE',
        LMS_USER: 'LMS_USER'
    }
};

export default Constants;